// ShadowInput – Local English-Chinese Dictionary
// ~600 most common English words for instant lookup (0 network latency).
// Exposed as window.ShadowInput.LocalDict

var ShadowInput = ShadowInput || {};

ShadowInput.LocalDict = (() => {
  // Format: word → { translation, phonetic, definition }
  const dict = {
    // Articles & determiners
    "a":{"t":"一个","p":"/eɪ/","d":"article: one"},
    "an":{"t":"一个","p":"/æn/","d":"article: one (before vowel)"},
    "the":{"t":"这/那","p":"/ðə/","d":"definite article"},
    "this":{"t":"这个","p":"/ðɪs/","d":"referring to something nearby"},
    "that":{"t":"那个","p":"/ðæt/","d":"referring to something distant"},
    "these":{"t":"这些","p":"/ðiːz/","d":"plural of this"},
    "those":{"t":"那些","p":"/ðoʊz/","d":"plural of that"},
    "some":{"t":"一些","p":"/sʌm/","d":"an unspecified amount"},
    "any":{"t":"任何","p":"/ˈeni/","d":"one or some regardless of quantity"},
    "every":{"t":"每个","p":"/ˈevri/","d":"each one"},
    "each":{"t":"每个","p":"/iːtʃ/","d":"every individual one"},
    "all":{"t":"所有","p":"/ɔːl/","d":"the whole amount"},
    "both":{"t":"两者","p":"/boʊθ/","d":"two things together"},
    "few":{"t":"很少","p":"/fjuː/","d":"a small number"},
    "many":{"t":"许多","p":"/ˈmeni/","d":"a large number"},
    "much":{"t":"很多","p":"/mʌtʃ/","d":"a large amount"},
    "more":{"t":"更多","p":"/mɔːr/","d":"a greater amount"},
    "most":{"t":"最多","p":"/moʊst/","d":"greatest in amount"},
    "other":{"t":"其他","p":"/ˈʌðər/","d":"additional or different"},
    "another":{"t":"另一个","p":"/əˈnʌðər/","d":"one more"},
    "such":{"t":"这样的","p":"/sʌtʃ/","d":"of that kind"},
    "no":{"t":"没有","p":"/noʊ/","d":"not any"},

    // Pronouns
    "i":{"t":"我","p":"/aɪ/","d":"first person singular"},
    "me":{"t":"我（宾格）","p":"/miː/","d":"object form of I"},
    "my":{"t":"我的","p":"/maɪ/","d":"belonging to me"},
    "myself":{"t":"我自己","p":"/maɪˈself/","d":"reflexive form of I"},
    "we":{"t":"我们","p":"/wiː/","d":"first person plural"},
    "us":{"t":"我们（宾格）","p":"/ʌs/","d":"object form of we"},
    "our":{"t":"我们的","p":"/aʊər/","d":"belonging to us"},
    "you":{"t":"你","p":"/juː/","d":"second person"},
    "your":{"t":"你的","p":"/jɔːr/","d":"belonging to you"},
    "yourself":{"t":"你自己","p":"/jɔːrˈself/","d":"reflexive form of you"},
    "he":{"t":"他","p":"/hiː/","d":"male third person"},
    "him":{"t":"他（宾格）","p":"/hɪm/","d":"object form of he"},
    "his":{"t":"他的","p":"/hɪz/","d":"belonging to him"},
    "she":{"t":"她","p":"/ʃiː/","d":"female third person"},
    "her":{"t":"她/她的","p":"/hɜːr/","d":"object/possessive of she"},
    "it":{"t":"它","p":"/ɪt/","d":"third person neuter"},
    "its":{"t":"它的","p":"/ɪts/","d":"belonging to it"},
    "they":{"t":"他们","p":"/ðeɪ/","d":"third person plural"},
    "them":{"t":"他们（宾格）","p":"/ðem/","d":"object form of they"},
    "their":{"t":"他们的","p":"/ðer/","d":"belonging to them"},
    "who":{"t":"谁","p":"/huː/","d":"asking about a person"},
    "what":{"t":"什么","p":"/wʌt/","d":"asking about a thing"},
    "which":{"t":"哪个","p":"/wɪtʃ/","d":"asking to choose"},
    "where":{"t":"哪里","p":"/wer/","d":"asking about place"},
    "when":{"t":"什么时候","p":"/wen/","d":"asking about time"},
    "why":{"t":"为什么","p":"/waɪ/","d":"asking for reason"},
    "how":{"t":"怎么","p":"/haʊ/","d":"asking about manner"},
    "someone":{"t":"某人","p":"/ˈsʌmwʌn/","d":"an unspecified person"},
    "something":{"t":"某事","p":"/ˈsʌmθɪŋ/","d":"an unspecified thing"},
    "everyone":{"t":"每个人","p":"/ˈevriwʌn/","d":"all people"},
    "everything":{"t":"一切","p":"/ˈevriθɪŋ/","d":"all things"},
    "nothing":{"t":"什么都没有","p":"/ˈnʌθɪŋ/","d":"not anything"},
    "anything":{"t":"任何事","p":"/ˈeniθɪŋ/","d":"any thing at all"},

    // Common verbs
    "be":{"t":"是/存在","p":"/biː/","d":"to exist or have identity"},
    "is":{"t":"是","p":"/ɪz/","d":"third person singular of be"},
    "are":{"t":"是","p":"/ɑːr/","d":"plural/second person of be"},
    "was":{"t":"是（过去）","p":"/wɒz/","d":"past tense of be (singular)"},
    "were":{"t":"是（过去）","p":"/wɜːr/","d":"past tense of be (plural)"},
    "been":{"t":"是（过去分词）","p":"/bɪn/","d":"past participle of be"},
    "have":{"t":"有","p":"/hæv/","d":"to possess or experience"},
    "has":{"t":"有","p":"/hæz/","d":"third person singular of have"},
    "had":{"t":"有（过去）","p":"/hæd/","d":"past tense of have"},
    "do":{"t":"做","p":"/duː/","d":"to perform an action"},
    "does":{"t":"做","p":"/dʌz/","d":"third person singular of do"},
    "did":{"t":"做（过去）","p":"/dɪd/","d":"past tense of do"},
    "done":{"t":"完成","p":"/dʌn/","d":"past participle of do"},
    "say":{"t":"说","p":"/seɪ/","d":"to speak words"},
    "said":{"t":"说（过去）","p":"/sed/","d":"past tense of say"},
    "get":{"t":"得到","p":"/ɡet/","d":"to obtain or receive"},
    "got":{"t":"得到（过去）","p":"/ɡɒt/","d":"past tense of get"},
    "make":{"t":"制作/使","p":"/meɪk/","d":"to create or cause"},
    "made":{"t":"制作（过去）","p":"/meɪd/","d":"past tense of make"},
    "go":{"t":"去","p":"/ɡoʊ/","d":"to move or travel"},
    "went":{"t":"去（过去）","p":"/went/","d":"past tense of go"},
    "gone":{"t":"去（过去分词）","p":"/ɡɒn/","d":"past participle of go"},
    "know":{"t":"知道","p":"/noʊ/","d":"to have knowledge of"},
    "knew":{"t":"知道（过去）","p":"/njuː/","d":"past tense of know"},
    "think":{"t":"想/认为","p":"/θɪŋk/","d":"to use the mind"},
    "thought":{"t":"想（过去）","p":"/θɔːt/","d":"past tense of think"},
    "take":{"t":"拿/花费","p":"/teɪk/","d":"to grasp or require"},
    "took":{"t":"拿（过去）","p":"/tʊk/","d":"past tense of take"},
    "taken":{"t":"拿（过去分词）","p":"/ˈteɪkən/","d":"past participle of take"},
    "see":{"t":"看","p":"/siː/","d":"to perceive with eyes"},
    "saw":{"t":"看（过去）","p":"/sɔː/","d":"past tense of see"},
    "seen":{"t":"看（过去分词）","p":"/siːn/","d":"past participle of see"},
    "come":{"t":"来","p":"/kʌm/","d":"to move toward"},
    "came":{"t":"来（过去）","p":"/keɪm/","d":"past tense of come"},
    "want":{"t":"想要","p":"/wɒnt/","d":"to desire"},
    "look":{"t":"看/看起来","p":"/lʊk/","d":"to direct eyes or seem"},
    "use":{"t":"使用","p":"/juːz/","d":"to employ for a purpose"},
    "used":{"t":"使用（过去）","p":"/juːzd/","d":"past tense of use"},
    "find":{"t":"找到","p":"/faɪnd/","d":"to discover"},
    "found":{"t":"找到（过去）","p":"/faʊnd/","d":"past tense of find"},
    "give":{"t":"给","p":"/ɡɪv/","d":"to hand over"},
    "gave":{"t":"给（过去）","p":"/ɡeɪv/","d":"past tense of give"},
    "given":{"t":"给（过去分词）","p":"/ˈɡɪvən/","d":"past participle of give"},
    "tell":{"t":"告诉","p":"/tel/","d":"to communicate information"},
    "told":{"t":"告诉（过去）","p":"/toʊld/","d":"past tense of tell"},
    "work":{"t":"工作","p":"/wɜːrk/","d":"to do labor"},
    "call":{"t":"叫/打电话","p":"/kɔːl/","d":"to name or phone"},
    "try":{"t":"尝试","p":"/traɪ/","d":"to attempt"},
    "ask":{"t":"问","p":"/æsk/","d":"to request information"},
    "need":{"t":"需要","p":"/niːd/","d":"to require"},
    "feel":{"t":"感觉","p":"/fiːl/","d":"to experience emotion or sensation"},
    "felt":{"t":"感觉（过去）","p":"/felt/","d":"past tense of feel"},
    "become":{"t":"变成","p":"/bɪˈkʌm/","d":"to come to be"},
    "leave":{"t":"离开","p":"/liːv/","d":"to go away from"},
    "left":{"t":"离开（过去）","p":"/left/","d":"past tense of leave"},
    "put":{"t":"放","p":"/pʊt/","d":"to place"},
    "mean":{"t":"意思是","p":"/miːn/","d":"to intend or signify"},
    "meant":{"t":"意思是（过去）","p":"/ment/","d":"past tense of mean"},
    "keep":{"t":"保持","p":"/kiːp/","d":"to retain or continue"},
    "kept":{"t":"保持（过去）","p":"/kept/","d":"past tense of keep"},
    "let":{"t":"让","p":"/let/","d":"to allow"},
    "begin":{"t":"开始","p":"/bɪˈɡɪn/","d":"to start"},
    "began":{"t":"开始（过去）","p":"/bɪˈɡæn/","d":"past tense of begin"},
    "show":{"t":"展示","p":"/ʃoʊ/","d":"to display"},
    "hear":{"t":"听到","p":"/hɪər/","d":"to perceive sound"},
    "heard":{"t":"听到（过去）","p":"/hɜːrd/","d":"past tense of hear"},
    "play":{"t":"玩/演奏","p":"/pleɪ/","d":"to engage in fun or music"},
    "run":{"t":"跑","p":"/rʌn/","d":"to move fast on foot"},
    "ran":{"t":"跑（过去）","p":"/ræn/","d":"past tense of run"},
    "move":{"t":"移动","p":"/muːv/","d":"to change position"},
    "live":{"t":"生活/住","p":"/lɪv/","d":"to be alive or reside"},
    "believe":{"t":"相信","p":"/bɪˈliːv/","d":"to accept as true"},
    "hold":{"t":"拿住","p":"/hoʊld/","d":"to keep in hand"},
    "bring":{"t":"带来","p":"/brɪŋ/","d":"to carry to a place"},
    "brought":{"t":"带来（过去）","p":"/brɔːt/","d":"past tense of bring"},
    "happen":{"t":"发生","p":"/ˈhæpən/","d":"to take place"},
    "write":{"t":"写","p":"/raɪt/","d":"to form letters or text"},
    "wrote":{"t":"写（过去）","p":"/roʊt/","d":"past tense of write"},
    "sit":{"t":"坐","p":"/sɪt/","d":"to be in a seated position"},
    "sat":{"t":"坐（过去）","p":"/sæt/","d":"past tense of sit"},
    "stand":{"t":"站","p":"/stænd/","d":"to be upright"},
    "stood":{"t":"站（过去）","p":"/stʊd/","d":"past tense of stand"},
    "lose":{"t":"失去/输","p":"/luːz/","d":"to be deprived of"},
    "lost":{"t":"失去（过去）","p":"/lɒst/","d":"past tense of lose"},
    "change":{"t":"改变","p":"/tʃeɪndʒ/","d":"to make different"},
    "learn":{"t":"学习","p":"/lɜːrn/","d":"to gain knowledge"},
    "learned":{"t":"学习（过去）","p":"/lɜːrnd/","d":"past tense of learn"},
    "read":{"t":"读","p":"/riːd/","d":"to interpret written text"},
    "spend":{"t":"花费","p":"/spend/","d":"to use time or money"},
    "spent":{"t":"花费（过去）","p":"/spent/","d":"past tense of spend"},
    "grow":{"t":"成长","p":"/ɡroʊ/","d":"to increase or develop"},
    "grew":{"t":"成长（过去）","p":"/ɡruː/","d":"past tense of grow"},
    "open":{"t":"打开","p":"/ˈoʊpən/","d":"to unfasten or start"},
    "walk":{"t":"走","p":"/wɔːk/","d":"to move on foot"},
    "stop":{"t":"停止","p":"/stɒp/","d":"to cease"},
    "start":{"t":"开始","p":"/stɑːrt/","d":"to begin"},
    "wait":{"t":"等待","p":"/weɪt/","d":"to stay in expectation"},
    "talk":{"t":"谈话","p":"/tɔːk/","d":"to speak"},
    "turn":{"t":"转","p":"/tɜːrn/","d":"to rotate"},
    "help":{"t":"帮助","p":"/help/","d":"to assist"},
    "watch":{"t":"看/观看","p":"/wɒtʃ/","d":"to observe"},
    "follow":{"t":"跟随","p":"/ˈfɒloʊ/","d":"to go after"},
    "eat":{"t":"吃","p":"/iːt/","d":"to consume food"},
    "ate":{"t":"吃（过去）","p":"/eɪt/","d":"past tense of eat"},
    "drink":{"t":"喝","p":"/drɪŋk/","d":"to consume liquid"},
    "drank":{"t":"喝（过去）","p":"/dræŋk/","d":"past tense of drink"},
    "sleep":{"t":"睡觉","p":"/sliːp/","d":"to rest in unconscious state"},
    "slept":{"t":"睡觉（过去）","p":"/slept/","d":"past tense of sleep"},
    "think":{"t":"认为","p":"/θɪŋk/","d":"to consider or believe"},
    "love":{"t":"爱","p":"/lʌv/","d":"to feel deep affection"},
    "like":{"t":"喜欢","p":"/laɪk/","d":"to find pleasant"},
    "hate":{"t":"恨","p":"/heɪt/","d":"to feel strong dislike"},
    "enjoy":{"t":"享受","p":"/ɪnˈdʒɔɪ/","d":"to take pleasure in"},
    "visit":{"t":"参观","p":"/ˈvɪzɪt/","d":"to go to see"},
    "travel":{"t":"旅行","p":"/ˈtrævəl/","d":"to go on a journey"},
    "meet":{"t":"遇见","p":"/miːt/","d":"to encounter"},
    "met":{"t":"遇见（过去）","p":"/met/","d":"past tense of meet"},
    "remember":{"t":"记住","p":"/rɪˈmembər/","d":"to recall"},
    "forget":{"t":"忘记","p":"/fərˈɡet/","d":"to fail to remember"},
    "forgot":{"t":"忘记（过去）","p":"/fərˈɡɒt/","d":"past tense of forget"},
    "understand":{"t":"理解","p":"/ˌʌndərˈstænd/","d":"to comprehend"},
    "understood":{"t":"理解（过去）","p":"/ˌʌndərˈstʊd/","d":"past tense of understand"},
    "create":{"t":"创建","p":"/kriˈeɪt/","d":"to make something new"},
    "share":{"t":"分享","p":"/ʃer/","d":"to give a portion of"},
    "build":{"t":"建造","p":"/bɪld/","d":"to construct"},
    "built":{"t":"建造（过去）","p":"/bɪlt/","d":"past tense of build"},

    // Common nouns
    "time":{"t":"时间","p":"/taɪm/","d":"the ongoing sequence of events"},
    "year":{"t":"年","p":"/jɪər/","d":"365 days"},
    "day":{"t":"天","p":"/deɪ/","d":"24-hour period"},
    "week":{"t":"周","p":"/wiːk/","d":"7-day period"},
    "month":{"t":"月","p":"/mʌnθ/","d":"about 30 days"},
    "hour":{"t":"小时","p":"/aʊər/","d":"60 minutes"},
    "minute":{"t":"分钟","p":"/ˈmɪnɪt/","d":"60 seconds"},
    "second":{"t":"秒","p":"/ˈsekənd/","d":"1/60 of a minute"},
    "morning":{"t":"早晨","p":"/ˈmɔːrnɪŋ/","d":"early part of the day"},
    "afternoon":{"t":"下午","p":"/ˌæftərˈnuːn/","d":"midday to evening"},
    "evening":{"t":"晚上","p":"/ˈiːvnɪŋ/","d":"late part of the day"},
    "night":{"t":"夜晚","p":"/naɪt/","d":"dark hours"},
    "today":{"t":"今天","p":"/təˈdeɪ/","d":"this present day"},
    "yesterday":{"t":"昨天","p":"/ˈjestərdeɪ/","d":"the day before today"},
    "tomorrow":{"t":"明天","p":"/təˈmɒroʊ/","d":"the day after today"},
    "person":{"t":"人","p":"/ˈpɜːrsən/","d":"a human being"},
    "people":{"t":"人们","p":"/ˈpiːpəl/","d":"human beings collectively"},
    "man":{"t":"男人","p":"/mæn/","d":"adult male"},
    "woman":{"t":"女人","p":"/ˈwʊmən/","d":"adult female"},
    "child":{"t":"孩子","p":"/tʃaɪld/","d":"a young person"},
    "children":{"t":"孩子们","p":"/ˈtʃɪldrən/","d":"plural of child"},
    "family":{"t":"家庭","p":"/ˈfæməli/","d":"parents and children"},
    "friend":{"t":"朋友","p":"/frend/","d":"a close companion"},
    "home":{"t":"家","p":"/hoʊm/","d":"where one lives"},
    "house":{"t":"房子","p":"/haʊs/","d":"a building to live in"},
    "city":{"t":"城市","p":"/ˈsɪti/","d":"a large urban area"},
    "country":{"t":"国家","p":"/ˈkʌntri/","d":"a nation"},
    "world":{"t":"世界","p":"/wɜːrld/","d":"the earth and all on it"},
    "place":{"t":"地方","p":"/pleɪs/","d":"a specific location"},
    "way":{"t":"方式","p":"/weɪ/","d":"a method or road"},
    "life":{"t":"生活","p":"/laɪf/","d":"the state of being alive"},
    "hand":{"t":"手","p":"/hænd/","d":"the body part at arm's end"},
    "eye":{"t":"眼睛","p":"/aɪ/","d":"organ for seeing"},
    "face":{"t":"脸","p":"/feɪs/","d":"the front of the head"},
    "head":{"t":"头","p":"/hed/","d":"top of the body"},
    "heart":{"t":"心","p":"/hɑːrt/","d":"organ pumping blood"},
    "mind":{"t":"心思","p":"/maɪnd/","d":"the thinking faculty"},
    "body":{"t":"身体","p":"/ˈbɒdi/","d":"the physical structure"},
    "food":{"t":"食物","p":"/fuːd/","d":"things people eat"},
    "water":{"t":"水","p":"/ˈwɔːtər/","d":"H₂O liquid"},
    "money":{"t":"钱","p":"/ˈmʌni/","d":"currency"},
    "school":{"t":"学校","p":"/skuːl/","d":"place for education"},
    "work":{"t":"工作","p":"/wɜːrk/","d":"employment or labor"},
    "job":{"t":"工作","p":"/dʒɒb/","d":"a position of employment"},
    "book":{"t":"书","p":"/bʊk/","d":"a written or printed work"},
    "car":{"t":"汽车","p":"/kɑːr/","d":"motor vehicle"},
    "road":{"t":"道路","p":"/roʊd/","d":"a path for vehicles"},
    "door":{"t":"门","p":"/dɔːr/","d":"an entrance"},
    "room":{"t":"房间","p":"/ruːm/","d":"a space in a building"},
    "story":{"t":"故事","p":"/ˈstɔːri/","d":"an account of events"},
    "name":{"t":"名字","p":"/neɪm/","d":"what someone is called"},
    "word":{"t":"单词","p":"/wɜːrd/","d":"a unit of language"},
    "idea":{"t":"想法","p":"/aɪˈdɪə/","d":"a thought or concept"},
    "question":{"t":"问题","p":"/ˈkwestʃən/","d":"something asked"},
    "answer":{"t":"回答","p":"/ˈænsər/","d":"a reply"},
    "problem":{"t":"问题","p":"/ˈprɒbləm/","d":"a difficulty to solve"},
    "thing":{"t":"事物","p":"/θɪŋ/","d":"an object or matter"},
    "part":{"t":"部分","p":"/pɑːrt/","d":"a piece of something"},
    "end":{"t":"结束","p":"/end/","d":"the final point"},
    "side":{"t":"侧面","p":"/saɪd/","d":"a surface or edge"},
    "point":{"t":"观点/点","p":"/pɔɪnt/","d":"a specific location or idea"},
    "fact":{"t":"事实","p":"/fækt/","d":"something known to be true"},
    "reason":{"t":"原因","p":"/ˈriːzən/","d":"a cause or explanation"},
    "number":{"t":"数字","p":"/ˈnʌmbər/","d":"a mathematical value"},
    "kind":{"t":"种类","p":"/kaɪnd/","d":"a type or variety"},
    "line":{"t":"线","p":"/laɪn/","d":"a long mark or row"},
    "air":{"t":"空气","p":"/er/","d":"the atmosphere"},
    "light":{"t":"光","p":"/laɪt/","d":"electromagnetic radiation"},
    "music":{"t":"音乐","p":"/ˈmjuːzɪk/","d":"organized sound"},
    "video":{"t":"视频","p":"/ˈvɪdioʊ/","d":"recorded visual content"},
    "photo":{"t":"照片","p":"/ˈfoʊtoʊ/","d":"a photograph"},
    "view":{"t":"景色/观点","p":"/vjuː/","d":"a sight or opinion"},
    "trip":{"t":"旅行","p":"/trɪp/","d":"a journey"},
    "street":{"t":"街道","p":"/striːt/","d":"a public road in a town"},
    "plan":{"t":"计划","p":"/plæn/","d":"an intention or design"},
    "example":{"t":"例子","p":"/ɪɡˈzæmpəl/","d":"a representative case"},
    "information":{"t":"信息","p":"/ˌɪnfərˈmeɪʃən/","d":"facts or data"},
    "experience":{"t":"经历","p":"/ɪkˈspɪəriəns/","d":"direct observation of events"},
    "moment":{"t":"时刻","p":"/ˈmoʊmənt/","d":"a very brief period"},
    "situation":{"t":"情况","p":"/ˌsɪtʃuˈeɪʃən/","d":"a set of circumstances"},
    "city":{"t":"城市","p":"/ˈsɪti/","d":"a large urban settlement"},
    "town":{"t":"小镇","p":"/taʊn/","d":"a small urban settlement"},
    "area":{"t":"地区","p":"/ˈeəriə/","d":"a region or zone"},
    "language":{"t":"语言","p":"/ˈlæŋɡwɪdʒ/","d":"a system of communication"},

    // Common adjectives
    "good":{"t":"好","p":"/ɡʊd/","d":"of high quality"},
    "great":{"t":"很棒","p":"/ɡreɪt/","d":"very good or large"},
    "new":{"t":"新","p":"/njuː/","d":"recently made"},
    "old":{"t":"旧/老","p":"/oʊld/","d":"having existed for a long time"},
    "big":{"t":"大","p":"/bɪɡ/","d":"of large size"},
    "small":{"t":"小","p":"/smɔːl/","d":"of little size"},
    "large":{"t":"大","p":"/lɑːrdʒ/","d":"of considerable size"},
    "little":{"t":"小/少","p":"/ˈlɪtəl/","d":"small in size or amount"},
    "long":{"t":"长","p":"/lɒŋ/","d":"of great length or duration"},
    "short":{"t":"短","p":"/ʃɔːrt/","d":"of little length or duration"},
    "high":{"t":"高","p":"/haɪ/","d":"far up"},
    "low":{"t":"低","p":"/loʊ/","d":"near the ground"},
    "right":{"t":"对/右","p":"/raɪt/","d":"correct or the right side"},
    "wrong":{"t":"错误","p":"/rɒŋ/","d":"not correct"},
    "real":{"t":"真实","p":"/riːl/","d":"actually existing"},
    "true":{"t":"真的","p":"/truː/","d":"in accordance with fact"},
    "false":{"t":"假的","p":"/fɔːls/","d":"not true"},
    "important":{"t":"重要","p":"/ɪmˈpɔːrtənt/","d":"of great significance"},
    "different":{"t":"不同","p":"/ˈdɪfrənt/","d":"not the same"},
    "same":{"t":"相同","p":"/seɪm/","d":"identical"},
    "own":{"t":"自己的","p":"/oʊn/","d":"belonging to oneself"},
    "free":{"t":"自由/免费","p":"/friː/","d":"not restricted or costing nothing"},
    "easy":{"t":"容易","p":"/ˈiːzi/","d":"not difficult"},
    "hard":{"t":"难/硬","p":"/hɑːrd/","d":"difficult or firm"},
    "fast":{"t":"快","p":"/fæst/","d":"moving quickly"},
    "slow":{"t":"慢","p":"/sloʊ/","d":"not fast"},
    "happy":{"t":"快乐","p":"/ˈhæpi/","d":"feeling joy"},
    "sad":{"t":"悲伤","p":"/sæd/","d":"feeling sorrow"},
    "beautiful":{"t":"美丽","p":"/ˈbjuːtɪfəl/","d":"very attractive"},
    "amazing":{"t":"令人惊叹","p":"/əˈmeɪzɪŋ/","d":"causing wonder"},
    "interesting":{"t":"有趣","p":"/ˈɪntrəstɪŋ/","d":"holding attention"},
    "funny":{"t":"有趣/好笑","p":"/ˈfʌni/","d":"causing laughter"},
    "serious":{"t":"严肃","p":"/ˈsɪəriəs/","d":"not playful"},
    "special":{"t":"特别","p":"/ˈspeʃəl/","d":"distinct from others"},
    "simple":{"t":"简单","p":"/ˈsɪmpəl/","d":"easy to understand"},
    "sure":{"t":"确定","p":"/ʃʊər/","d":"certain"},
    "ready":{"t":"准备好","p":"/ˈredi/","d":"fully prepared"},
    "able":{"t":"能够","p":"/ˈeɪbəl/","d":"having the ability"},
    "young":{"t":"年轻","p":"/jʌŋ/","d":"not old"},
    "full":{"t":"满","p":"/fʊl/","d":"containing everything possible"},
    "early":{"t":"早","p":"/ˈɜːrli/","d":"before the usual time"},
    "late":{"t":"晚","p":"/leɪt/","d":"after the expected time"},
    "next":{"t":"下一个","p":"/nekst/","d":"immediately following"},
    "last":{"t":"最后","p":"/lɑːst/","d":"coming at the end"},
    "first":{"t":"第一","p":"/fɜːrst/","d":"before all others"},
    "second":{"t":"第二","p":"/ˈsekənd/","d":"after the first"},
    "best":{"t":"最好","p":"/best/","d":"of the highest quality"},
    "better":{"t":"更好","p":"/ˈbetər/","d":"of higher quality"},
    "worse":{"t":"更差","p":"/wɜːrs/","d":"of lower quality"},
    "worst":{"t":"最差","p":"/wɜːrst/","d":"of the lowest quality"},
    "beautiful":{"t":"美丽","p":"/ˈbjuːtɪfəl/","d":"pleasing to the senses"},
    "popular":{"t":"流行","p":"/ˈpɒpjələr/","d":"liked by many people"},
    "local":{"t":"当地","p":"/ˈloʊkəl/","d":"relating to a nearby area"},
    "national":{"t":"国家的","p":"/ˈnæʃənəl/","d":"relating to a nation"},
    "public":{"t":"公共","p":"/ˈpʌblɪk/","d":"available to everyone"},
    "private":{"t":"私人","p":"/ˈpraɪvɪt/","d":"not for public use"},
    "possible":{"t":"可能","p":"/ˈpɒsɪbəl/","d":"able to happen"},
    "perfect":{"t":"完美","p":"/ˈpɜːrfɪkt/","d":"without flaw"},
    "certain":{"t":"确定","p":"/ˈsɜːrtən/","d":"known for sure"},
    "clear":{"t":"清晰","p":"/klɪər/","d":"easy to understand or see"},
    "close":{"t":"近/关闭","p":"/kloʊs/","d":"near or to shut"},
    "common":{"t":"普通","p":"/ˈkɒmən/","d":"happening frequently"},

    // Common adverbs
    "very":{"t":"非常","p":"/ˈveri/","d":"to a high degree"},
    "really":{"t":"真的","p":"/ˈriːəli/","d":"in reality; very"},
    "just":{"t":"只是/刚刚","p":"/dʒʌst/","d":"exactly; only; recently"},
    "also":{"t":"也","p":"/ˈɔːlsoʊ/","d":"in addition"},
    "too":{"t":"也/太","p":"/tuː/","d":"additionally; excessively"},
    "only":{"t":"只","p":"/ˈoʊnli/","d":"and no one or nothing else"},
    "still":{"t":"仍然","p":"/stɪl/","d":"continuing or even now"},
    "already":{"t":"已经","p":"/ɔːlˈredi/","d":"before now"},
    "even":{"t":"甚至","p":"/ˈiːvən/","d":"used for emphasis"},
    "never":{"t":"从不","p":"/ˈnevər/","d":"at no time"},
    "always":{"t":"总是","p":"/ˈɔːlweɪz/","d":"at all times"},
    "often":{"t":"经常","p":"/ˈɒfən/","d":"many times"},
    "sometimes":{"t":"有时","p":"/ˈsʌmtaɪmz/","d":"occasionally"},
    "usually":{"t":"通常","p":"/ˈjuːʒuəli/","d":"in most cases"},
    "now":{"t":"现在","p":"/naʊ/","d":"at this moment"},
    "then":{"t":"然后","p":"/ðen/","d":"at that time; next"},
    "here":{"t":"这里","p":"/hɪər/","d":"in this place"},
    "there":{"t":"那里","p":"/ðer/","d":"in that place"},
    "back":{"t":"回/背","p":"/bæk/","d":"to the rear; to return"},
    "out":{"t":"出去","p":"/aʊt/","d":"away from inside"},
    "up":{"t":"向上","p":"/ʌp/","d":"toward a higher place"},
    "down":{"t":"向下","p":"/daʊn/","d":"toward a lower place"},
    "away":{"t":"离开","p":"/əˈweɪ/","d":"to a distance"},
    "together":{"t":"一起","p":"/təˈɡeðər/","d":"in company"},
    "actually":{"t":"实际上","p":"/ˈæktʃuəli/","d":"in fact"},
    "basically":{"t":"基本上","p":"/ˈbeɪsɪkli/","d":"fundamentally"},
    "probably":{"t":"可能","p":"/ˈprɒbəbli/","d":"almost certainly"},
    "especially":{"t":"特别是","p":"/ɪˈspeʃəli/","d":"above all; particularly"},
    "finally":{"t":"最终","p":"/ˈfaɪnəli/","d":"at the end"},
    "suddenly":{"t":"突然","p":"/ˈsʌdənli/","d":"quickly and unexpectedly"},
    "slowly":{"t":"慢慢地","p":"/ˈsloʊli/","d":"at a slow pace"},
    "quickly":{"t":"快速地","p":"/ˈkwɪkli/","d":"at a fast pace"},
    "almost":{"t":"几乎","p":"/ˈɔːlmoʊst/","d":"very nearly"},
    "maybe":{"t":"也许","p":"/ˈmeɪbi/","d":"perhaps"},
    "quite":{"t":"相当","p":"/kwaɪt/","d":"to a considerable degree"},
    "enough":{"t":"足够","p":"/ɪˈnʌf/","d":"as much as needed"},
    "well":{"t":"好","p":"/wel/","d":"in a good manner"},
    "around":{"t":"周围","p":"/əˈraʊnd/","d":"in a circle or nearby"},
    "again":{"t":"再次","p":"/əˈɡen/","d":"one more time"},
    "however":{"t":"然而","p":"/haʊˈevər/","d":"despite that"},
    "instead":{"t":"代替","p":"/ɪnˈsted/","d":"in place of something"},
    "though":{"t":"虽然","p":"/ðoʊ/","d":"despite the fact that"},
    "although":{"t":"尽管","p":"/ɔːlˈðoʊ/","d":"in spite of the fact"},

    // Prepositions & conjunctions
    "in":{"t":"在...里","p":"/ɪn/","d":"inside or within"},
    "on":{"t":"在...上","p":"/ɒn/","d":"on the surface of"},
    "at":{"t":"在（时间/地点）","p":"/æt/","d":"indicating location or time"},
    "for":{"t":"为了","p":"/fɔːr/","d":"intended to belong to"},
    "with":{"t":"和/用","p":"/wɪð/","d":"accompanied by"},
    "about":{"t":"关于","p":"/əˈbaʊt/","d":"on the subject of"},
    "after":{"t":"在...之后","p":"/ˈæftər/","d":"following in time"},
    "before":{"t":"在...之前","p":"/bɪˈfɔːr/","d":"earlier than"},
    "between":{"t":"在...之间","p":"/bɪˈtwiːn/","d":"in the middle of two"},
    "through":{"t":"穿过","p":"/θruː/","d":"from one side to another"},
    "during":{"t":"在...期间","p":"/ˈdjʊərɪŋ/","d":"throughout a time"},
    "without":{"t":"没有","p":"/wɪˈðaʊt/","d":"not having"},
    "under":{"t":"在...下面","p":"/ˈʌndər/","d":"below"},
    "over":{"t":"超过/在上方","p":"/ˈoʊvər/","d":"above or more than"},
    "into":{"t":"进入","p":"/ˈɪntuː/","d":"to the inside of"},
    "from":{"t":"从","p":"/frɒm/","d":"indicating origin"},
    "by":{"t":"由/旁边","p":"/baɪ/","d":"next to or via"},
    "as":{"t":"作为/当","p":"/æz/","d":"in the role of"},
    "of":{"t":"的","p":"/ɒv/","d":"expressing relationship"},
    "to":{"t":"到","p":"/tuː/","d":"in the direction of"},
    "and":{"t":"和","p":"/ænd/","d":"connecting words or clauses"},
    "but":{"t":"但是","p":"/bʌt/","d":"however; except"},
    "or":{"t":"或者","p":"/ɔːr/","d":"alternatively"},
    "if":{"t":"如果","p":"/ɪf/","d":"on condition that"},
    "because":{"t":"因为","p":"/bɪˈkɒz/","d":"for the reason that"},
    "so":{"t":"所以","p":"/soʊ/","d":"therefore"},
    "while":{"t":"当...时","p":"/waɪl/","d":"during the time that"},
    "since":{"t":"自从","p":"/sɪns/","d":"from a time in the past"},
    "until":{"t":"直到","p":"/ənˈtɪl/","d":"up to the time that"},
    "than":{"t":"比","p":"/ðæn/","d":"used in comparisons"},
    "like":{"t":"像","p":"/laɪk/","d":"similar to"},
    "across":{"t":"穿过","p":"/əˈkrɒs/","d":"from one side to the other"},
    "against":{"t":"反对","p":"/əˈɡenst/","d":"in opposition to"},
    "along":{"t":"沿着","p":"/əˈlɒŋ/","d":"in a line with"},
    "near":{"t":"近","p":"/nɪər/","d":"close to"},
    "off":{"t":"离开","p":"/ɒf/","d":"away from"},
    "behind":{"t":"在...后面","p":"/bɪˈhaɪnd/","d":"at the back of"},
    "within":{"t":"在...内","p":"/wɪˈðɪn/","d":"inside the bounds of"},

    // Modal verbs
    "can":{"t":"能","p":"/kæn/","d":"be able to"},
    "could":{"t":"能（过去）","p":"/kʊd/","d":"past form of can"},
    "will":{"t":"将会","p":"/wɪl/","d":"future intention"},
    "would":{"t":"会","p":"/wʊd/","d":"conditional form of will"},
    "should":{"t":"应该","p":"/ʃʊd/","d":"ought to"},
    "must":{"t":"必须","p":"/mʌst/","d":"have to"},
    "may":{"t":"可以/也许","p":"/meɪ/","d":"be allowed to; perhaps"},
    "might":{"t":"可能","p":"/maɪt/","d":"possibility"},
    "shall":{"t":"将","p":"/ʃæl/","d":"used for future or obligation"},
    "not":{"t":"不","p":"/nɒt/","d":"negation"},
  };

  /**
   * Look up a word (case-insensitive).
   * Returns { translation, phonetic, definition } or null if not found.
   */
  function lookup(word) {
    const entry = dict[word.toLowerCase()];
    if (!entry) return null;
    return {
      translation: entry.t,
      phonetic: entry.p,
      definition: entry.d,
    };
  }

  /** Check if a word is in the local dictionary. */
  function has(word) {
    return Object.prototype.hasOwnProperty.call(dict, word.toLowerCase());
  }

  return { lookup, has };
})();
